### ISSUE TITLE
Material Handlers?

### ISSUE THREAD

**Issue by Jayshua83** [FearlessNite345/Liquid-Lime#2]
What does the Material Handlers do?

I was looking into adding Liquid Lime to my map which should be an easy task but I wasn't sure what the material handler did and if it was needed if I just add FillType and SprayType to my map!

Thanks for the info!

**Comment by FearlessNite345** [comment]
The material handler is for the spray effect coming out of sprayers if you don't have it then it will not show any effect when spraying the easiest way to add it to a map by default would be to just put all the mod files excluding the modDesc into the map folder and then just point the map modDesc to the files

**Comment by FearlessNite345** [comment]
at this time i will be closing this issue as i have provided details on what it is for
