### ISSUE TITLE
The mod wont load in the sim (fix is in comment)

### ISSUE THREAD

**Issue by CAC14** [FearlessNite345/Liquid-Lime#5]
farming sim 22 on steam does not like the "-" in the name.  I renamed it to fS22_Liquid_Lime and it worked fine.

**Comment by FearlessNite345** [comment]
If you download the zip file from the releases tab there is no "-"

**Comment by CAC14** [comment]
Needs to be fixed on https://www.modhub.us/

But I also didn't get it to work right.  It just fertilized my fields even when i put the lime spray into a self propelled sprayer.  It did not remove needs lime.

**Comment by FearlessNite345** [comment]
I didn't post it there my official version is on Kingmods and GitHub and I haven't had time to update this recently but I will soon
